set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_scan_sig[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {column_scan_sig[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {column_scan_sig[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {column_scan_sig[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {column_scan_sig[3]}]
set_property PACKAGE_PIN G2 [get_ports {column_scan_sig[3]}]
set_property PACKAGE_PIN C1 [get_ports {column_scan_sig[1]}]
set_property PACKAGE_PIN H1 [get_ports {column_scan_sig[0]}]
set_property PACKAGE_PIN B4 [get_ports {row_scan_sig[0]}]
set_property PACKAGE_PIN A4 [get_ports {row_scan_sig[1]}]
set_property PACKAGE_PIN A3 [get_ports {row_scan_sig[2]}]
set_property PACKAGE_PIN B1 [get_ports {row_scan_sig[3]}]
set_property PACKAGE_PIN A1 [get_ports {row_scan_sig[4]}]
set_property PACKAGE_PIN B3 [get_ports {row_scan_sig[5]}]
set_property PACKAGE_PIN B2 [get_ports {row_scan_sig[6]}]
set_property PACKAGE_PIN D5 [get_ports {row_scan_sig[7]}]
create_interface interface_display
set_property PACKAGE_PIN C2 [get_ports {column_scan_sig[2]}]


set_property IOSTANDARD LVCMOS33 [get_ports {number_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {number_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports auxn1]
set_property IOSTANDARD LVCMOS33 [get_ports auxp1]
set_property PACKAGE_PIN C12 [get_ports auxp1]

set_property MARK_DEBUG true [get_nets ready]
set_property MARK_DEBUG true [get_nets {data[6]}]
set_property MARK_DEBUG true [get_nets {data[14]}]
set_property MARK_DEBUG true [get_nets {data[9]}]
set_property MARK_DEBUG true [get_nets {data[13]}]
set_property MARK_DEBUG true [get_nets {data[11]}]
set_property MARK_DEBUG true [get_nets {data[5]}]
set_property MARK_DEBUG true [get_nets {data[8]}]
set_property MARK_DEBUG true [get_nets {data[4]}]
set_property MARK_DEBUG true [get_nets {data[12]}]
set_property MARK_DEBUG true [get_nets {data[10]}]
set_property MARK_DEBUG true [get_nets {data[15]}]
set_property MARK_DEBUG true [get_nets {data[7]}]
set_property MARK_DEBUG false [get_nets clk_IBUF_BUFG]
set_property MARK_DEBUG true [get_nets clk_IBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {data[4]} {data[5]} {data[6]} {data[7]} {data[8]} {data[9]} {data[10]} {data[11]} {data[12]} {data[13]} {data[14]} {data[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list clk_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list ready]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
