# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.cache/wt [current_project]
set_property parent.project_path C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.srcs/sources_1/new/frequencymeter.v
  C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.srcs/sources_1/new/frequencycalculate.v
  C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.srcs/sources_1/new/frequencybcd.v
  C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.srcs/sources_1/new/digital.v
  C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.srcs/sources_1/new/main.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.srcs/constrs_1/new/frequency.xdc
set_property used_in_implementation false [get_files C:/Users/Think/Desktop/17.5.9/frequency_meter/frequency_meter.srcs/constrs_1/new/frequency.xdc]


synth_design -top main -part xc7a35tcsg324-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
