set_property PACKAGE_PIN K2 [get_ports led_check]
set_property PACKAGE_PIN F6 [get_ports led_green]
set_property PACKAGE_PIN G4 [get_ports led_red]
set_property PACKAGE_PIN G3 [get_ports led_yello]
set_property PACKAGE_PIN P5 [get_ports sw_green]
set_property PACKAGE_PIN P4 [get_ports sw_red]
set_property PACKAGE_PIN P3 [get_ports sw_yello]
set_property IOSTANDARD LVCMOS33 [get_ports led_check]
set_property IOSTANDARD LVCMOS33 [get_ports led_green]
set_property IOSTANDARD LVCMOS33 [get_ports led_red]
set_property IOSTANDARD LVCMOS33 [get_ports led_yello]
set_property IOSTANDARD LVCMOS33 [get_ports sw_green]
set_property IOSTANDARD LVCMOS33 [get_ports sw_red]
set_property IOSTANDARD LVCMOS33 [get_ports sw_yello]


set_property PACKAGE_PIN B1 [get_ports {display_out[3]}]
set_property PACKAGE_PIN A4 [get_ports {display_out[5]}]
set_property PACKAGE_PIN B4 [get_ports {display_out[6]}]
set_property PACKAGE_PIN H1 [get_ports {display_out[7]}]
set_property PACKAGE_PIN C1 [get_ports {display_out[8]}]
set_property PACKAGE_PIN C2 [get_ports {display_out[9]}]
set_property PACKAGE_PIN G2 [get_ports {display_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[0]}]
set_property PACKAGE_PIN P17 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]


set_property PACKAGE_PIN A3 [get_ports {display_out[4]}]
set_property PACKAGE_PIN A1 [get_ports {display_out[2]}]
set_property PACKAGE_PIN B3 [get_ports {display_out[1]}]
set_property PACKAGE_PIN B2 [get_ports {display_out[0]}]
