# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir M:/Xilinx/projects/new/new.cache/wt [current_project]
set_property parent.project_path M:/Xilinx/projects/new/new.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo m:/Xilinx/projects/new/new.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib M:/Xilinx/projects/new/new.srcs/sources_1/new/new.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc M:/Xilinx/projects/new/new.srcs/constrs_1/new/new.xdc
set_property used_in_implementation false [get_files M:/Xilinx/projects/new/new.srcs/constrs_1/new/new.xdc]


synth_design -top new -part xc7a35tcsg324-1


write_checkpoint -force -noxdef new.dcp

catch { report_utilization -file new_utilization_synth.rpt -pb new_utilization_synth.pb }
