set_property PACKAGE_PIN L1 [get_ports {out[2]}]
set_property PACKAGE_PIN M1 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN K3 [get_ports {out[0]}]

set_property PACKAGE_PIN F6 [get_ports {show[7]}]
set_property PACKAGE_PIN G4 [get_ports {show[6]}]
set_property PACKAGE_PIN G3 [get_ports {show[5]}]
set_property PACKAGE_PIN J4 [get_ports {show[4]}]
set_property PACKAGE_PIN H4 [get_ports {show[3]}]
set_property PACKAGE_PIN J3 [get_ports {show[2]}]
set_property PACKAGE_PIN J2 [get_ports {show[1]}]
set_property PACKAGE_PIN K2 [get_ports {show[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {show[0]}]
set_property PACKAGE_PIN K1 [get_ports error]
set_property IOSTANDARD LVCMOS33 [get_ports error]

set_property PACKAGE_PIN B1 [get_ports {display_out[3]}]
set_property PACKAGE_PIN A4 [get_ports {display_out[5]}]
set_property PACKAGE_PIN B4 [get_ports {display_out[6]}]
set_property PACKAGE_PIN H1 [get_ports {display_out[7]}]
set_property PACKAGE_PIN C1 [get_ports {display_out[8]}]
set_property PACKAGE_PIN C2 [get_ports {display_out[9]}]
set_property PACKAGE_PIN G2 [get_ports {display_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[0]}]
set_property PACKAGE_PIN P17 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]


set_property PACKAGE_PIN A3 [get_ports {display_out[4]}]
set_property PACKAGE_PIN A1 [get_ports {display_out[2]}]
set_property PACKAGE_PIN B3 [get_ports {display_out[1]}]
set_property PACKAGE_PIN B2 [get_ports {display_out[0]}]

set_property PACKAGE_PIN G1 [get_ports {display_out2[10]}]
set_property PACKAGE_PIN F1 [get_ports {display_out2[9]}]
set_property PACKAGE_PIN E1 [get_ports {display_out2[8]}]
set_property PACKAGE_PIN G6 [get_ports {display_out2[7]}]
set_property PACKAGE_PIN D4 [get_ports {display_out2[6]}]
set_property PACKAGE_PIN E3 [get_ports {display_out2[5]}]
set_property PACKAGE_PIN D3 [get_ports {display_out2[4]}]
set_property PACKAGE_PIN F4 [get_ports {display_out2[3]}]
set_property PACKAGE_PIN F3 [get_ports {display_out2[2]}]
set_property PACKAGE_PIN E2 [get_ports {display_out2[1]}]
set_property PACKAGE_PIN D2 [get_ports {display_out2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[0]}]
set_property PACKAGE_PIN R15 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports button]

set_property PACKAGE_PIN H6 [get_ports sign]
set_property IOSTANDARD LVCMOS33 [get_ports sign]

set_property PACKAGE_PIN H5 [get_ports sign1]
set_property IOSTANDARD LVCMOS33 [get_ports sign1]

set_property PACKAGE_PIN D14 [get_ports siginal]
set_property IOSTANDARD LVCMOS33 [get_ports siginal]

set_property PACKAGE_PIN A15 [get_ports test]
set_property IOSTANDARD LVCMOS33 [get_ports test]

set_property PACKAGE_PIN D5 [get_ports {display_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out[11]}]
set_property PACKAGE_PIN H2 [get_ports {display_out2[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display_out2[11]}]